services:
  - type: web
    name: g-event-bot-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    autoDeploy: true 