services:
  - type: web
    name: g-event-bot-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webapp:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 